from agents.base import BaseAgent
from pydantic import BaseModel, Field
from typing import List

class ReviewerOutputSchema(BaseModel):
    passed: bool = Field(
        description="True if all agent drafts are cohesive, realistic, and free of contradictions. False if revision is needed."
    )
    feedback_comments: List[str] = Field(
        description="List of critiques, mathematical checks, or alignment errors found between the different plans."
    )
    rework_needed: bool = Field(
        description="True if an agent must make edits before final approval; False otherwise."
    )
    target_agent: str = Field(
        description="The agent that must perform the rework: 'Research Agent', 'Finance Agent', 'Marketing Agent', or 'None'."
    )

class ReviewerAgent(BaseAgent):
    def __init__(self, client, model="gemini-2.5-flash"):
        super().__init__(client, model)
        self.system_instruction = (
            "You are the Lead Investment Reviewer and Auditor at DreamForge AI.\n"
            "Your role is to cross-examine and critique the plans generated by the other agents.\n"
            "Look specifically for inconsistencies and unrealistic estimates:\n"
            "1. Financial Contradictions: Does the Marketing Agent's budget match the operational budget in the Finance plan?\n"
            "2. Market Misalignment: Does the Research Agent's customer segment align with the Marketing Agent's target personas?\n"
            "3. Over-optimism: Are the customer growth rates or starting prices realistic given the competitive landscape?\n"
            "If any critical flaw is found, set passed = false, rework_needed = true, specify the target_agent, "
            "and list clear actionable points in feedback_comments.\n"
            "If the plans look aligned, set passed = true, rework_needed = false, target_agent = 'None'."
        )

    def audit_drafts(self, idea, planner_data, research_data, finance_data, marketing_data):
        user_content = (
            f"Startup Idea: {idea}\n\n"
            f"Planner Summary: {planner_data}\n\n"
            f"Research Draft: {research_data}\n\n"
            f"Finance Draft: {finance_data}\n\n"
            f"Marketing Draft: {marketing_data}\n\n"
            "Review these drafts for coherence. Do the numbers and target personas align? Provide your audit result."
        )
        result = self.generate_structured(self.system_instruction, user_content, ReviewerOutputSchema)
        return result
